version: 2
jobs:
  build:
    working_directory: ~/libx
    docker:
      - image: openjdk:8
    environment:
      # Suppresses warnings
      LEIN_ROOT: nbd
      # Allows tests to pass with snapshot lib versions used in project
      LEIN_SNAPSHOTS_IN_RELEASE: true
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: bin/lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run: bin/lein do test :only libx.core-test, uberjar
      - store_artifacts:
          path: target/libx.jar
          destination: uberjar
